flask3/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')
class CommentsForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flask3/main/routes.py
from flask import render_template, request, Blueprint
from flask3.models import Post,Comment

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
       
    comments =Comment.query.all()
    return render_template('home.html', posts=posts,comments=comments)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

flask3/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)

from flask_login import current_user, login_required
from flask3 import db
from flask3.models import Post,Comment
from flask3.posts.forms import PostForm, CommentsForm



posts = Blueprint('posts', __name__)


@posts.route('/post/new',methods=['GET','POST'])
@login_required
def new_post():
    form= PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html',title='New Post',form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))




@posts.route('/post/comments',methods=['GET','POST'])
@login_required
def comments():    
    form= CommentsForm()  
    if form.validate_on_submit():
        new_comment = Comment(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(new_comment)
        db.session.commit()
        flash('Your comment has been created!','success')
        return redirect(url_for('main.home'))
    return render_template('comments.html',title='Comment',form=form, legend='New comment')

flask3/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask3 import db, bcrypt
from flask3.models import User, Post
from flask3.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flask3.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register',methods=['GET','POST'])
def register():
   if current_user.is_authenticated:
       return redirect(url_for('main.home'))
   form =RegistrationForm()
   if form.validate_on_submit():
       hashed_password =bcrypt.generate_password_hash(form.password.data).decode('utf-8')
       user= User(username=form.username.data, email=form.email.data, password=hashed_password)
       db.session.add(user)
       db.session.commit()
       flash('Your account has been created! You are now able to log in', 'success')
       return redirect(url_for('users.login'))

   return render_template('register.html',title="register", form= form)

@users.route('/login',methods=['GET','POST'])
def login():
  if current_user.is_authenticated:
      return redirect(url_for('main.home'))
  form =LoginForm()
  if form.validate_on_submit():
      user = User.query.filter_by(email=form.email.data).first()
      if user and bcrypt.check_password_hash(user.password, form.password.data):
         login_user(user, remember=form.remember.data)
         next_page = request.args.get('next')
         return  redirect(next_page) if next_page else redirect(url_for('main.home'))
       
      else:       
          flash('Login Unsuccessful. Please check username and password', 'danger')

  return render_template('login.html',title="Login", form= form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account",methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username= form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method =='GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',image_file= image_file,form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)



@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)



@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flask3/templates/about.html
{% extends "layout.html"%}
{%block content%}

<h1>Goal</h1>
<p>The purpose of this independent project is to demonstrate your understanding of the content you covered throughout the week.</p> 
<h3>Overall Project Description</h3>
<p>In life, you only have 60 seconds to impress someone. 1 minute can make or break you. How do we make sure that you use your 1 minute to actually say something meaningful?</p>

<p>Your task this week is to create an application that allows users to use that one minute wisely. The users will submit their one minute pitches and other users will vote on them and leave comments to give their feedback on them.</p>

<p>The pitches are organized by category. You can have different categories like pickup lines, interview pitch, product pitch, promotion pitch.(You don't have to use these categories, you can come up with your own creative categories) </p>

<p>The pitches should be arranged by category and the new posts should be displayed first.</p>
{% endblock content%}

flask3/templates/account.html
{% extends "layout.html"%}
{%block content%}

<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{current_user.username}}</h2>
      <p class="text-secondary">{{current_user.email}}</p>
    </div>
  </div>
  <!-- FORM HERE -->
 
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Account Info</legend>
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}

            {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>
        <div class="form-group">
          {{ form.picture.label() }}
          {{ form.picture(class="form-control-file") }}
          {% if form.picture.errors %}
              {% for error in form.picture.errors %}
                  <span class="text-danger">{{ error }}</span><br>
              {% endfor %}
          {% endif %}
      </div>
       
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>


</div>


{% endblock content%}

flask3/templates/category.html
{% extends "layout.html" %}

{% block content%} 
    <h2 class="mb-4 mt-2 pt-2"> Pitches in {{category}} </h2>

    {% for post in post %}

    <article class="media content-section">
      <img class="rounded-circle article-img" src="https://source.unsplash.com/125x125/?profile,photo" alt="{{ post.author.username }} profile photo">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted mr-2">{{ post.posted_date.strftime('%Y-%m-%d') }}</small>
                <small class="mr-2">Posted in: <a class="mr-2" href="{{ url_for('posts.category_post', category=post.category) }}">{{ post.category }}</a></small>

              </div>
              <h2><a class="article-title mt-2" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content }}</p>
            </div>
            <p class="article-footer"><a class="ratings" href="{{ url_for('posts.new_comment') }}"> Leave a comment</a></p>
    </article>
    {% endfor %}
    

{% endblock content %}
       

flask3/templates/comments.html
{% extends "layout.html" %}
{% block content %}


<ul class="nav nav-tabs nav-justified" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#General" role="tab">General</a>
    </li>
    <li class="nav-item tab">
      <a class="nav-link" data-toggle="tab" href="#Products" role="tab">Products</a>
    </li>
    <li class="nav-item tab">
      <a class="nav-link" data-toggle="tab" href="#Pickups" role="tab">Entertainment</a>
    </li>
    <li class="nav-item tab">
      <a class="nav-link" data-toggle="tab" href="#Interviews" role="tab">Sports</a>
    </li>
    <li class="nav-item tab">
      <a class="nav-link" data-toggle="tab" href="#Promotions" role="tab">Products</a>
    </li>
  </ul>
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
      
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flask3/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

<ul class="nav nav-tabs nav-justified" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#General" role="tab">General</a>
    </li>
    <li class="nav-item tab">
      <a class="nav-link" data-toggle="tab" href="#Products" role="tab">Products</a>
    </li>
    <li class="nav-item tab">
      <a class="nav-link" data-toggle="tab" href="#Pickups" role="tab">Entertainment</a>
    </li>
    <li class="nav-item tab">
      <a class="nav-link" data-toggle="tab" href="#Interviews" role="tab">Sports</a>
    </li>
    <li class="nav-item tab">
      <a class="nav-link" data-toggle="tab" href="#Promotions" role="tab">Products</a>
    </li>
  </ul>
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flask3/templates/home.html
{% extends "layout.html"%}
{%block content%}

<!-- Header Showcase -->
<header id="showcase" class="grid">
  <div class="bg-image"></div>
  <div class="content-wrap">
    <h1 id="w">Welcome to Pitch Solutions</h1>
   
    <a href="{{ url_for('main.about')}}" class="btn">Read More</a>
  </div>
</header>

<!-- Main Area -->

 {% for post in posts.items%}

 <article class="media content-section">
 <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
   <div class="media-body">
     <div class="article-metadata">
       <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
       <small class="text-muted">{{ post.date_posted.strftime("%d %B, %Y") }}</small>
     </div>
     <h2><a class="article-title" href="{{url_for('posts.post',post_id=post.id)}}">{{ post.title }}</a></h2>
     <p class="article-content">{{ post.content }}</p>
   
     
   </div>
   
   

   <li class="list-group-item" style="font-size: 14px; color: dodgerblue;">
           <ul class="list-group list-group-flush">
                  <a href="">
                    <span id="upvote" class="fas fa-thumbs-up"></span>
                </a>&ensp;
                <a href="">
                    <span id="downvote" class="fas fa-thumbs-down"></span>
                </a>&ensp;
                <a href="{{ url_for('posts.comments') }}">
                    <span class="fas fa-comments"></span>
                 
                </a>
            </li>
            
        </ul>
        
        <div id="app">
          <div class="container-fluid">
            <ul class="list-group">
              <post v-for="post in posts" :post="post"></post>
            </ul>
          </div>
        </div>
        
        <template id="post-template">
          <li class="list-group-item">
            <i class="glyphicon glyphicon-chevron-up" @click="upvote"></i>
            <span class="label label-primary">{{ votes }}</span>
            <i class="glyphicon glyphicon-chevron-down" @click="downvote"></i>
            <a>{{ post.title }}</a>
          </li>
        </template>
      </li>
 </article>
 
    
 {%endfor%}
 {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
 {% if page_num %}
   {% if posts.page == page_num %}
     <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
   {% else %}
     <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
   {% endif %}
 {% else %}
   ...
 {% endif %}
{% endfor %}
{% endblock content%}

flask3/templates/layout.html
<!doctype html>
<html lang="en">

<head>
  {%if title%}
  <title>flaskblog {{title }}</title>

  {%else%}
  <title> pitches</title>
  {%endif%}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://fonts.googleapis.com/css?family=Cookie|Niconne&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Courgette&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <script src="{{ url_for('static', filename='js.js') }}"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/"> pitches</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home')}}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about')}}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{url_for('posts.comments') }}">comments</a>
            <a class="nav-item nav-link" href="{{url_for('posts.new_post') }}">New pitch</a>
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login')  }}">Login</a>
            <a class="nav-item nav-link" href="{{url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

  <main role="main" class="container">
    <div class="row">
      <div class="col-md-12">

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
  
    </div>

    
  </main>

  <!-- Optional JavaScript -->
  <script>

  </script>

  <script   src="https://code.jquery.com/jquery-3.3.1.min.js"   integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="   crossorigin="anonymous"></script>
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

flask3/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6">
    <div class="content-section">
   
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
    
    </div>
    <div class="col-md-4">
        <div class="content-section">
          <h3>Pitch by signing in</h3>
          <p class='text-muted'>
            <ul class="list-group">
                <img src="https://bit.ly/2YNMS7l" width="109" style="border-radius:50%;">
                <img src="https://bit.ly/2zpKwR8" width="109" style="border-radius:50%;">
                <img src="https://bit.ly/2zs8FGI" width="109" style="border-radius:50%;">
                <img src="https://bit.ly/2WH6yqx" width="109" style="border-radius:50%;">
                
                <div class="icon">
                    <span>
                        <a href="#" class="fa fa-facebook"></a>
                        <a href="#" class="fa fa-twitter"></a>
                        <a href="#" class="fa fa-google"></a>
                        <a href="#" class="fa fa-linkedin"></a>
                        <a href="#" class="fa fa-youtube"></a>
                    </span>
                </div>
            </ul>
          </p>
        </div>
      </div>
    </div>
    
{% endblock content %}

flask3/templates/post.html
{% extends "layout.html" %}
{% block content %}

  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

flask3/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}